"""Every past incident stays fixed: replays each minimal harmful call through the current gate.

Generated by evals/incidents.py from real harmful runs. A policy or contract
change that would let any of them through fails this suite.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from evals.incidents import gate_decision
from evals.scenarios import SCENARIOS

CASES = [c for f in sorted((Path(__file__).parent / "incidents").glob("*.json")) for c in json.loads(f.read_text())]
BY_ID = {s["id"]: s for s in SCENARIOS}


@pytest.mark.parametrize("case", [c for c in CASES if not c["needs_judge"]], ids=lambda c: f"{c['id']} {','.join(c['harms'])}")
def test_incident_never_allowed_again(case, record):
    decision = gate_decision(BY_ID[case["scenario"]], case["tool"], case["args"])
    record("incidents", "negative", decision != "allow")
    assert decision != "allow", f"regression: {case['id']} ({case['harms']}) is allowed again"


def test_incident_inventory():
    judge_only = [c["id"] for c in CASES if c["needs_judge"]]
    print(f"\n{len(CASES)} incident reproducers, {len(judge_only)} covered only by the AI judge: {judge_only}")
